[package]
name = "sparkplug-rs"
version = "0.1.0"
edition = "2021"
license = "EPL-2.0"
readme = "README.md"
repository = "https://github.com/ahlner/sparkplug-rs"

[dependencies]
protobuf = "2.27.1"

[build-dependencies]
protoc-rust = "2.27.1"